services:
#Server is the name of the service or job.
  web:
    build:
#builds a docker image in the found docker file in the current directory.
      context: .
      dockerfile: Dockerfile
#Maps current directory to /app in docker file container.
    volumes: 
      - .:/app
#Command to run when running docker image.
    command: python -m http.server
#Maps port to flask app.
    ports:
      - 8000:8000
